"use strict";

// This public assessment uses portable fields that can later map into a fuller manuscript intake/MOS workflow.
const model = { project_stage:"", publication_type:"", publication_language:"", concept_summary:"", audience_types:[], geographic_market:"", niche_level:3, author_authority:[], author_establishment:"", author_platform:[], material_volume:"", development_needs:[], development_openness:"", market_awareness:"", success_goal:[], previous_barriers:[], why_exists:[], diagnostic_view:{} };
const $ = (selector) => document.querySelector(selector);
const app = $("#app"); let step = 0;
const fiction = ["Fiction — literary/general","Fiction — romance","Fiction — crime/thriller","Fiction — other genre"];
const options = {
 stage:["idea only","notes/research/talks/articles/material","started manuscript","completed first draft","fairly polished manuscript","previously submitted to publisher/agent","some version already published"],
 type:[...fiction,"Memoir/autobiography/biography","Family history/genealogy","General nonfiction","Academic/specialist knowledge for a broader audience","History/politics/current affairs","Religion/philosophy/ideas","Business/professional","Self-development/practical","Technical/professional work or manual","Educational/textbook","Children's book","Young adult","Illustrated/visual book","Other / not sure yet"],
 language:["Afrikaans","English","another language","multilingual","undecided"],
 why:["untold/poorly told story","useful expertise/knowledge","distinctive argument/viewpoint","make difficult subject accessible","identifiable audience demand","entertainment/escapism","preserve personal/family/historical story","unusual experience/access","not sure yet","other"],
 readers:["general adult readers","subject-interest readers","professionals","academics/students","young adults","children","Afrikaans readers","South African readers","international English-language readers","cultural/religious/interest community","existing followers/clients/students/customers","don't know yet","other"],
 reach:["local/regional","South Africa","Southern Africa/Africa","international","specialist/professional community irrespective of country","don't know"],
 authority:["formal qualifications","professional experience","many years in field","original research","lived/personal experience","unusual access","previous books","articles/papers/published writing","teaching/training/public speaking","recognised reputation","existing audience/community","strong storytelling ability","no formal authority, but worthwhile story/idea","other"],
 established:["interested outsider","interested and learning","some relevant experience","well-established in a field or community","recognised specialist or practitioner","significant public/professional reputation"],
 platform:["newsletter","social following","professional network","academic network","clients/customers","students","speaking engagements","media exposure","religious/community organisation","existing readers","none yet"],
 material:["idea only","notes/fragments","<10k words","10k–30k","30k–60k",">60k","complete manuscript","substantial non-text material such as audio/video/research"],
 needs:["defining the book","structure","more writing","research","developmental editing","cutting/tightening","making specialist material accessible","improving prose","fact/evidence checking","audience identification","commercial positioning","publishing/distribution","unsure"],
 openness:["strongly open","open within reason","prefer light changes","not looking for substantial changes"],
 market:["yes and know differentiation","yes but differentiation still developing","probably but not researched","don't know any","believe nothing quite like it exists"],
 success:["commercial sales","small but important audience","international readership","professional reputation","influence debate/public understanding","support existing profession/business","preserve legacy/story","establish author identity","create series/body of work","simply reach readers","unsure"],
 barriers:["didn't know where to start","difficulty turning knowledge/material into a book","lack of time","started/stopped repeatedly","structure/writing problems","publisher/agent rejection","little/no response from publishers","assumed publishers would not be interested","cost concerns","don't understand publishing process","nothing; only starting now","other"]
};
function esc(value){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function choices(key, items, multi=false, limit=0){const selected=model[key]|| (multi?[]:"");return `<div class="option-grid" id="group-${key}">${items.map((v,i)=>`<label class="option"><input type="${multi?"checkbox":"radio"}" name="${key}" aria-describedby="${key}-error" value="${esc(v)}" ${multi?selected.includes(v)?"checked":"":selected===v?"checked":""} ${limit?`data-limit="${limit}"`:""}><span>${esc(v)}</span></label>`).join("")}</div><p class="error group-error" id="${key}-error" role="alert" hidden></p>`;}
function q(title,help,body){return `<h2 class="question-title" tabindex="-1">${title}</h2><p class="question-help">${help||""}</p>${body}`;}
function textarea(key,label,help){return `<div class="field"><label for="${key}">${label}</label><textarea id="${key}" data-text="${key}" maxlength="1000" placeholder="Write plainly; a rough description is fine.">${esc(model[key]||"")}</textarea><small>${help||""}</small></div>`;}
function isFiction(){return fiction.includes(model.publication_type);}
function fields(){switch(step){
case 0:return q("Where is the project now?","Choose the closest description.",choices("project_stage",options.stage));
case 1:return q("What kind of book is it?","If it crosses categories, choose the closest starting point.",choices("publication_type",options.type));
case 2:return q("Language and the central idea","Tell us the intended publication language, then describe what a reader would get from this book.",choices("publication_language",options.language)+textarea("concept_summary","In one or two sentences, what is the book?","A simple description is enough."));
case 3:return q("Why this book, and for whom?","Choose as many as are useful.",`<h3>Why should this book exist?</h3>${choices("why_exists",options.why,true)}<h3 style="margin-top:24px">Intended readers</h3>${choices("audience_types",options.readers,true)}`);
case 4:return q("Audience and reach","Neither a specialist audience nor a broad audience is automatically better.",`<div class="field"><label for="niche">How specialised is the likely readership?</label><div class="range-row"><span>1 · very specialised</span><span>5 · very broad</span></div><input class="range" id="niche" type="range" min="1" max="5" value="${model.niche_level}" data-range="niche_level"></div><h3>Geographic/market reach</h3>${choices("geographic_market",options.reach)}`);
case 5:return q("Your fit for this project","Formal credentials are not the only kind of authority. Lived experience, storytelling and access can matter too.",`<h3>Author fit / authority</h3>${choices("author_authority",options.authority,true)}<h3 style="margin-top:24px">How established are you in this area?</h3>${choices("author_establishment",options.established)}`);
case 6:return q("Reach and current material","An existing platform can help, but having none yet does not rule a project out.",`<h3>Existing reach / platform</h3>${choices("author_platform",options.platform,true)}<h3 style="margin-top:24px">Current material</h3>${choices("material_volume",options.material)}`);
case 7:return q("What would help the project move forward?","Choose every development need that feels relevant.",`${choices("development_needs",options.needs,true)}<h3 style="margin-top:24px">Openness to substantial editorial change</h3>${choices("development_openness",options.openness)}`);
case 8:return q("Market awareness and your own definition of success","Knowing comparable books is useful; a project being unusual is not, by itself, a strength or a weakness.",`<h3>Awareness of comparable / competing books</h3>${choices("market_awareness",options.market)}<h3 style="margin-top:24px">Desired definition of success <small>(choose up to three)</small></h3>${choices("success_goal",options.success,true,3)}`);
case 9:return q("What has held it back?","This helps us understand the practical challenge, not judge the project.",choices("previous_barriers",options.barriers,true));
case 10:return branch(); default:return "";}}
function branch(){if(isFiction())return q("A little more about the fiction","These answers help us understand reader expectations.",`<h3>Strongest reader appeal</h3>${choices("fiction_appeal",["plot/suspense","romance","characters","humour","setting/world","emotional experience","genre satisfaction","unusual/original element","unsure"])}<h3 style="margin-top:24px">Clarity about genre / shelf</h3>${choices("genre_clarity",["very clear","roughly clear","not yet clear"])}`);if(model.publication_type==="Children's book")return q("A little more about the children's book","We are not trying to apply detailed children's-market scoring at this stage.",`<div class="field"><label for="age_range">Intended age range</label><input id="age_range" data-text="age_range" value="${esc(model.age_range||"")}" placeholder="For example: 5–7, middle grade, or young readers"></div><h3>Is illustration central to the book?</h3>${choices("illustration_central",["yes","no","not sure yet"])}`);return q("Ready for an initial view","Review your answers, then see a development-friendly initial assessment. A closer judgement would always require looking at the project or material itself.",`<div class="notice">Your answers remain in this browser for this assessment. They are not sent anywhere at this stage.</div>`);}
function persist(){app.querySelectorAll("input[type=radio]:checked").forEach(el=>model[el.name]=el.value);app.querySelectorAll(".option-grid").forEach(box=>{const c=box.querySelector("input[type=checkbox]");if(c)model[c.name]=[...box.querySelectorAll("input:checked")].map(el=>el.value)});app.querySelectorAll("[data-text]").forEach(el=>model[el.dataset.text]=el.value.trim());app.querySelectorAll("[data-range]").forEach(el=>model[el.dataset.range]=Number(el.value));}
function requiredFields(){let required=[];switch(step){case 0:required=["project_stage"];break;case 1:required=["publication_type"];break;case 2:required=["publication_language","concept_summary"];break;case 3:required=["why_exists","audience_types"];break;case 4:required=["geographic_market"];break;case 5:required=["author_authority","author_establishment"];break;case 6:required=["author_platform","material_volume"];break;case 7:required=["development_needs","development_openness"];break;case 8:required=["market_awareness","success_goal"];break;case 9:required=["previous_barriers"];break;case 10:if(isFiction())required=["fiction_appeal","genre_clarity"];if(model.publication_type==="Children's book")required=["age_range","illustration_central"];break;}return required;}
function missingFields(){return requiredFields().filter(key=>Array.isArray(model[key])?!model[key].length:!model[key]);}
function valid(){return missingFields().length===0;}
const validationMessages={
  project_stage:"Choose the closest description of your project stage.",publication_type:"Choose the closest type of book.",publication_language:"Choose the intended publication language.",concept_summary:"Add a short description of the book.",
  why_exists:"Choose at least one reason why this book should exist.",audience_types:"Choose at least one intended reader group.",geographic_market:"Choose the likely geographic or market reach.",
  author_authority:"Choose at least one way in which you are connected to or equipped for this project.",author_establishment:"Choose the closest description of how established you are in this area.",
  author_platform:"Choose your existing reach or platform, including none yet if appropriate.",material_volume:"Choose the amount of material you currently have.",
  development_needs:"Choose at least one area where the project needs development.",development_openness:"Choose how open you are to substantial editorial change.",
  market_awareness:"Choose your current awareness of comparable or competing books.",success_goal:"Choose up to three definitions of success, including at least one.",
  previous_barriers:"Choose what has held the project back, including only starting now if appropriate.",fiction_appeal:"Choose the strongest reader appeal.",genre_clarity:"Choose how clear the genre or shelf is.",age_range:"Add the intended age range.",illustration_central:"Choose whether illustration is central to the book."
};
function validateGroups(){
  const missing=missingFields();
  requiredFields().forEach(key=>{
    const controls=[...app.querySelectorAll(`[name="${key}"], [data-text="${key}"]`)];
    let error=app.querySelector(`#${key}-error`);
    if(!error&&controls.length){
      error=document.createElement("p");error.id=`${key}-error`;error.className="error group-error";error.setAttribute("role","alert");error.hidden=true;
      controls[0].insertAdjacentElement("afterend",error);
    }
    controls.forEach(control=>{
      const descriptions=new Set((control.getAttribute("aria-describedby")||"").split(/\s+/).filter(Boolean));descriptions.add(`${key}-error`);
      control.setAttribute("aria-describedby",[...descriptions].join(" "));
      if(missing.includes(key))control.setAttribute("aria-invalid","true");else control.removeAttribute("aria-invalid");
    });
    if(error){error.textContent=missing.includes(key)?validationMessages[key]:"";error.hidden=!missing.includes(key);}
  });
  $("#error").hidden=true;
  if(missing.length)app.querySelector(`[name="${missing[0]}"], [data-text="${missing[0]}"]`)?.focus();
  return missing.length===0;
}
function render(moveFocus=true){const total=11;app.innerHTML=`<div class="progress-top"><span>Step ${Math.min(step+1,total)} of ${total}</span><span>${Math.round((step+1)/total*100)}% complete</span></div><div class="progress" role="progressbar" aria-label="Assessment progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round((step+1)/total*100)}"><span style="width:${(step+1)/total*100}%"></span></div><div id="question">${fields()}</div><p class="error" id="error" role="alert" hidden>Please answer this question before continuing.</p><div class="actions"><button class="button secondary" id="back" ${step===0?"disabled":""}>Back</button><button class="button" id="next">${step===10?"See my initial view":"Continue"}</button></div>`;$("#back").onclick=()=>{persist();step--;render()};$("#next").onclick=()=>{persist();if(!validateGroups())return;if(step===10){results();return}step++;render()};app.querySelectorAll("input[data-limit]").forEach(el=>el.addEventListener("change",()=>{const checked=app.querySelectorAll(`input[name="${el.name}"]:checked`);if(checked.length>Number(el.dataset.limit)){el.checked=false;$("#error").textContent=`Please choose up to ${el.dataset.limit}.`;$("#error").hidden=false}}));if(moveFocus)focusContent();}
function focusContent(){
  const heading=app.querySelector(".question-title, .result-head h2");
  if(heading){heading.focus({preventScroll:true});heading.scrollIntoView({block:"start",behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}
}
const displayValues={
  "teaching/training/public speaking":"teaching, training or public-speaking experience","recognised reputation":"recognised standing in the field","existing audience/community":"an existing audience or community","lived/personal experience":"lived or personal experience","articles/papers/published writing":"published writing",
  "formal qualifications":"formal qualifications","professional experience":"professional experience","many years in field":"many years of experience in the field","original research":"original research","unusual access":"unusual access to the subject","previous books":"previous books","strong storytelling ability":"strong storytelling ability",
  "untold/poorly told story":"a story that has not yet been told well","useful expertise/knowledge":"useful knowledge or expertise","distinctive argument/viewpoint":"a distinctive argument or viewpoint","make difficult subject accessible":"making a difficult subject accessible","identifiable audience demand":"an identified demand from readers","entertainment/escapism":"entertainment or escapism","preserve personal/family/historical story":"preserving a personal, family or historical story","unusual experience/access":"unusual experience or access",
  "academics/students":"academics or students","cultural/religious/interest community":"a cultural, religious or interest community","existing followers/clients/students/customers":"existing followers, clients, students or customers","local/regional":"local or regional readers","Southern Africa/Africa":"Southern Africa or Africa","specialist/professional community irrespective of country":"a specialist or professional community across borders",
  "plot/suspense":"plot or suspense","setting/world":"setting or world-building","unusual/original element":"an unusual or original element",
  "idea only":"an idea","notes/fragments":"notes or fragments","<10k words":"fewer than 10,000 words",">60k":"more than 60,000 words","complete manuscript":"a complete manuscript","notes/research/talks/articles/material":"notes, research, talks or other material","started manuscript":"a manuscript in progress","completed first draft":"a completed first draft","fairly polished manuscript":"a fairly polished manuscript","previously submitted to publisher/agent":"a project previously submitted to a publisher or agent","some version already published":"a project with a version already published"
};
function human(value){return displayValues[value]||value.replaceAll("/", " or ");}
function humanList(values){return new Intl.ListFormat("en",{style:"long",type:"conjunction"}).format(values.map(human));}
function diagnose(){
  const reasons=(model.why_exists||[]).filter(x=>!["not sure yet","other"].includes(x));
  const readers=model.audience_types.filter(x=>!["don't know yet","other"].includes(x));
  const definedConcept=model.concept_summary.trim().split(/\s+/).length>=12 && reasons.length>0;
  const genreKnown=!isFiction()||(model.fiction_appeal!=="unsure"&&Boolean(model.fiction_appeal)&&model.genre_clarity==="very clear");
  const reachKnown=Boolean(model.geographic_market)&&model.geographic_market!=="don't know";
  const specificFit=model.author_authority.filter(x=>!["other","no formal authority, but worthwhile story/idea"].includes(x));
  const established=["well-established in a field or community","recognised specialist or practitioner","significant public/professional reputation"].includes(model.author_establishment);
  const strongFit=specificFit.length>1||(specificFit.length>0&&established);
  const audienceNeedsWork=model.development_needs.includes("audience identification");
  const open=["strongly open","open within reason"].includes(model.development_openness);
  const substantial=[options.material[4],options.material[5],"complete manuscript"].includes(model.material_volume);
  const early=["idea only","notes/fragments"].includes(model.material_volume)||!model.material_volume;
  const audienceClear=readers.length>0&&reachKnown&&!model.audience_types.includes("don't know yet")&&!audienceNeedsWork;
  const formatKnown=Boolean(model.publication_type)&&model.publication_type!=="Other / not sure yet"&&genreKnown&&(model.publication_type!=="Children's book"||(Boolean(model.age_range)&&["yes","no"].includes(model.illustration_central)));
  const goalKnown=model.success_goal.some(x=>x!=="unsure");
  const marketKnown=model.market_awareness==="yes and know differentiation";
  const view={
    concept:{name:"Concept",state:definedConcept&&genreKnown&&!model.why_exists.includes("not sure yet")?"Promising":reasons.length&&model.concept_summary.trim().split(/\s+/).length>=5?"Developing":"Needs definition",reason:""},
    audience:{name:"Audience",state:audienceClear?"Clear":readers.length||reachKnown?"Partly defined":"Needs work",reason:""},
    author_project_fit:{name:"Author-project fit",state:strongFit?"Strong":specificFit.length||model.author_authority.includes("no formal authority, but worthwhile story/idea")?"Relevant":"Needs context",reason:""},
    material_readiness:{name:"Material & readiness",state:substantial&&open?"Ready for closer assessment":early?"Early stage":"Development stage",reason:""},
    publishing_path:{name:"Publishing path",state:audienceClear&&formatKnown&&goalKnown&&marketKnown?"Fairly clear":readers.length||goalKnown||marketKnown?"Needs investigation":"Too early to decide",reason:""}
  };
  view.concept.reason=view.concept.state==="Promising"?`Your description gives an initial proposition, supported by your reason for the book: ${human(reasons[0])}. This signals a basis for discussion, not a judgement of the writing.`:view.concept.state==="Developing"?"You have supplied a proposition and a reason for the book, but the description or reader promise still needs clarification.":"The description or rationale is still too open to identify a clear book proposition. Define what the reader will gain and why the book should exist.";
  view.audience.reason=audienceNeedsWork&&readers.length?`You have identified plausible reader groups${reachKnown?" and a likely reach":""}, but you also indicated that the audience still needs work. The next step is to identify the primary reader the book is really for.`:readers.length?`You identify ${humanList(readers)}. ${audienceClear?`Your stated reach is ${human(model.geographic_market)}; a deliberately narrow readership can be a valid choice.`:"The likely reach or intended readership still needs clarification."}`:"The intended readers are not yet identified. Start with the people most likely to value this particular book, even if that is a small group.";
  view.author_project_fit.reason=specificFit.length?`You identify ${humanList(specificFit)} as relevant experience. ${strongFit?(established?"This is supported by your reported establishment in the field or community.":"These multiple grounds provide a basis for a closer look."):"A sample and more context would help establish how this connection supports the book."} Formal qualifications are not required.`:view.author_project_fit.state==="Relevant"?"You identify a worthwhile story or idea without formal authority. A sample and some context about your connection to the subject would help establish the fit.":"Your answers do not yet give specific context for your connection to this book. Lived experience, storytelling, community knowledge or unusual access can be as relevant as professional credentials.";
  view.material_readiness.reason=view.material_readiness.state==="Ready for closer assessment"?`You report ${human(model.material_volume)} and openness to editorial development. That is enough material for a closer look, without implying publication readiness.`:early?"You currently have an idea or fragments. This is a legitimate starting point: the next work is definition, structure and sample material.":`You report ${human(model.material_volume)}. ${open?"Developing the structure and material can prepare it for fuller assessment.":"A discussion about development needs and the scope of acceptable changes would help establish the next step."}`;
  view.publishing_path.reason=view.publishing_path.state==="Fairly clear"?"You identify readers, a book type, comparable-book differentiation and a success goal. These provide a starting point for discussing suitable routes; no route or publication outcome is implied.":view.publishing_path.state==="Needs investigation"?"There is a starting point in your audience, market awareness or success goals, but positioning and route options need investigation. Commercial, specialist and personal-publication aims can all be legitimate.":"Readers, comparable books and success aims are still uncertain. Define these before choosing a publication route.";
  model.diagnostic_view=view;
  return view;
}
function projectGuidance(view){
  const promising=[];
  if(model.publication_type==="Family history/genealogy")promising.push("Preservation and legacy are valid aims; family or community value need not depend on large commercial sales.");
  else if(model.success_goal.includes("preserve legacy/story"))promising.push("Preserving a person, body of work or story can be a legitimate aim even where the likely readership is specialised.");
  if(model.publication_type==="Academic/specialist knowledge for a broader audience")promising.push("For a specialist or knowledge-led book, credibility, clarity and value to a defined readership may matter more than mass-market scale.");
  if(model.publication_type==="Technical/professional work or manual")promising.push("A useful specialist book can serve a small readership well. The next assessment should consider expertise, evidence and practical usefulness.");
  if(isFiction()&&model.fiction_appeal!=="unsure")promising.push(`Your chosen reader appeal, ${human(model.fiction_appeal)}, offers a starting point for shaping the fiction.`);
  if(view.concept.state==="Promising")promising.push(`You have begun to articulate why the book should exist: ${human(model.why_exists.filter(x=>!["other","not sure yet"].includes(x))[0])}.`);
  if(view.author_project_fit.state==="Strong")promising.push(`Your stated ${human(model.author_authority.filter(x=>!["other","no formal authority, but worthwhile story/idea"].includes(x))[0])} gives us a concrete connection to explore through the material.`);
  if(view.audience.state==="Clear")promising.push("You have identified readers and a likely reach; neither a specialist nor a broad audience is automatically preferable.");
  if(model.author_platform.includes("none yet"))promising.push("No existing platform does not disqualify the project. Reader access can be developed alongside the book.");
  if(view.material_readiness.state==="Early stage")promising.push("Being early is not failure: definition and a small sample can make the next conversation useful.");
  if(promising.length<2)promising.push("Your answers provide a starting point for a development conversation; the actual material will be needed for an editorial judgement.");
  if(promising.length<2)promising.push(`Your stated project stage, ${human(model.project_stage)}, helps set a realistic starting point for that conversation.`);
  const tasks={"defining the book":"Write a concise proposition explaining the book and its reader benefit.",structure:"Prepare a provisional contents list or story outline.","more writing":"Develop representative sample material.",research:"Identify and plan the research still needed.","developmental editing":"Arrange a discussion of structure, argument or narrative development.","cutting/tightening":"Identify repetition and material that does not serve the central book.","making specialist material accessible":"Test a sample with the intended nonspecialist reader.","improving prose":"Prepare a representative passage for close editorial discussion.","fact/evidence checking":"Map claims and sources that require verification.","audience identification":"Describe a specific intended reader and why they would read this book.","commercial positioning":"Compare relevant books and explain what this project adds.","publishing/distribution":"Investigate publication and distribution options suited to your goals.",unsure:"Use a sample and outline to identify the most useful development work."};
  const development=[];
  if(view.concept.state==="Needs definition")development.push(tasks["defining the book"]);
  if(view.audience.state!=="Clear")development.push(tasks["audience identification"]);
  if(isFiction()&&model.genre_clarity!=="very clear")development.push("Clarify the genre or shelf and the reader experience the fiction promises.");
  model.development_needs.forEach(x=>{if(tasks[x])development.push(tasks[x]);});
  if(!model.market_awareness.startsWith("yes"))development.push(tasks["commercial positioning"]);
  if(view.material_readiness.state==="Early stage")development.push(tasks["more writing"]);
  if(model.previous_barriers.some(x=>["lack of time","started/stopped repeatedly"].includes(x)))development.push("Set a manageable writing milestone and a realistic schedule.");
  if(model.previous_barriers.includes("cost concerns"))development.push("Set a development budget before comparing service or publication options.");
  if(model.previous_barriers.some(x=>["publisher/agent rejection","little/no response from publishers"].includes(x)))development.push("Review the previous submissions and any responses before choosing another route.");
  let material=model.material_volume==="complete manuscript"||["completed first draft","fairly polished manuscript"].includes(model.project_stage)?"The manuscript and a short project summary.":view.material_readiness.state==="Early stage"?"A clearer proposition, rough structure and a small piece of sample material.":"Representative sample chapters or material, plus an outline of the whole book.";
  if(isFiction())material+=" Include genre positioning and the intended reader experience.";
  if(model.publication_type==="Children's book")material+=" Include the intended age range and illustration context with the manuscript or sample.";
  if(["Technical/professional work or manual","Academic/specialist knowledge for a broader audience"].includes(model.publication_type))material+=" Identify the intended reader, proposed structure, and the evidence or experience supporting the work.";
  const route=view.concept.state==="Needs definition"||view.material_readiness.state==="Early stage"?"Define and structure the book first.":view.audience.state!=="Clear"?"Audience and positioning work would be a useful next step.":view.material_readiness.state==="Ready for closer assessment"?"A closer manuscript assessment would help identify the development required.":view.publishing_path.state==="Fairly clear"?"A publication-path discussion alongside review of the available material would be useful.":"Developmental editing or manuscript development is the likely next conversation.";
  return {promising:promising.slice(0,4),development:[...new Set(development)].slice(0,4),material,route};
}
function results(){
  const view=diagnose(),guidance=projectGuidance(view);
  const heading=view.material_readiness.state==="Early stage"?"The project is still early, which means the next step is definition rather than publication.":view.concept.state==="Promising"&&view.audience.state==="Clear"&&view.material_readiness.state==="Ready for closer assessment"?"There is enough here to look more closely.":"This looks developable, but some fundamentals still need work.";
  app.innerHTML=`<section class="result-head"><p class="eyebrow">INITIAL PROJECT VIEW</p><h2 tabindex="-1">${heading}</h2><p>This is an initial development assessment based only on the information you supplied. It is not a publishing offer, manuscript evaluation or prediction of sales.</p></section>
  <div class="diagnostic-view">${Object.values(view).map(d=>`<section class="diagnostic"><h3>${esc(d.name)} <span>${esc(d.state)}</span></h3><p>${esc(d.reason)}</p></section>`).join("")}</div>
  <section class="guidance"><h2>What looks promising</h2><ul>${guidance.promising.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section>
  <section class="guidance"><h2>What needs development</h2><ul>${guidance.development.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section>
  <section class="guidance"><h2>What we would need to see next</h2><p>${esc(guidance.material)}</p></section>
  <section class="guidance route"><h2>A possible next step</h2><p>${esc(guidance.route)} This is not a promise of publication.</p></section>
<section class="contact"><h2>Would you like us to have a look?</h2><p>There is no charge for this initial contact or for us to decide whether we would like to see more. You are not committing to any paid service.</p><form id="contact-form" novalidate><div class="field"><label for="name">Name</label><input id="name" required></div><div class="field"><label for="email">Email</label><input id="email" type="email" required></div><div class="field"><label for="country">Country</label><input id="country" required></div><div class="field"><label for="preferred-language">Preferred language</label><input id="preferred-language" required></div><div class="field"><label for="phone">Optional phone / WhatsApp</label><input id="phone"></div><div class="field"><label for="note">Brief note</label><textarea id="note"></textarea></div><label class="checkbox"><input id="consent" type="checkbox" required><span>I consent to Clear Copy Clinic contacting me about this project.</span></label><p class="error" id="contact-error" role="alert" hidden>Please complete the required fields and consent to being contacted.</p><button class="button" style="margin-top:22px" type="submit">Send initial enquiry</button></form><p class="notice" style="margin-top:22px">For this MVP, the assessment is not stored or sent automatically. Contact details are prepared only when you choose to send this enquiry.</p></section>`;
  $("#contact-form").addEventListener("submit",contact);focusContent();
}
function contact(event){event.preventDefault();const f=event.currentTarget;if(!f.checkValidity()){$("#contact-error").hidden=false;return}const body=`Book project enquiry\n\nName: ${$("#name").value}\nEmail: ${$("#email").value}\nCountry: ${$("#country").value}\nPreferred language: ${$("#preferred-language").value}\nPhone/WhatsApp: ${$("#phone").value}\n\nProject stage: ${model.project_stage}\nPublication type: ${model.publication_type}\nPublication language: ${model.publication_language}\nConcept: ${model.concept_summary}\nIntended readers: ${model.audience_types.join("; ")}\nGeographic reach: ${model.geographic_market}\nMaterial volume: ${model.material_volume}\nDevelopment needs: ${model.development_needs.join("; ")}\nSuccess goals: ${model.success_goal.join("; ")}\n\nInitial qualitative diagnosis:\n${Object.values(model.diagnostic_view).map(d=>`${d.name}: ${d.state}`).join("\n")}\n\nNote: ${$("#note").value}`;window.location.href=`mailto:hello@clearcopy.clinic?subject=${encodeURIComponent("Book project initial enquiry")}&body=${encodeURIComponent(body)}`;}
render(false);
