"use strict";

// Kept as a flat, portable model so it can map directly into a future private MOS.
const model = { project_stage:"", publication_type:"", publication_language:"", concept_summary:"", audience_types:[], geographic_market:"", niche_level:3, author_authority:[], author_establishment:"", author_platform:[], material_volume:"", development_needs:[], development_openness:"", market_awareness:"", success_goal:[], previous_barriers:[], potential_scores:{} };
const $ = (selector) => document.querySelector(selector);
const app = $("#app"); let step = 0;
const fiction = ["Fiction — literary/general","Fiction — romance","Fiction — crime/thriller","Fiction — other genre"];
const options = {
 stage:["idea only","notes/research/talks/articles/material","started manuscript","completed first draft","fairly polished manuscript","previously submitted to publisher/agent","some version already published"],
 type:[...fiction,"Memoir/autobiography/biography","Family history/genealogy","General nonfiction","Academic/specialist knowledge for a broader audience","History/politics/current affairs","Religion/philosophy/ideas","Business/professional","Self-development/practical","Technical/professional work or manual","Educational/textbook","Children's book","Young adult","Illustrated/visual book","Other / not sure yet"],
 language:["Afrikaans","English","another language","multilingual","undecided"],
 why:["untold/poorly told story","useful expertise/knowledge","distinctive argument/viewpoint","make difficult subject accessible","identifiable audience demand","entertainment/escapism","preserve personal/family/historical story","unusual experience/access","not sure yet","other"],
 readers:["general adult readers","subject-interest readers","professionals","academics/students","young adults","children","Afrikaans readers","South African readers","international English-language readers","cultural/religious/interest community","existing followers/clients/students/customers","don't know yet","other"],
 reach:["local/regional","South Africa","Southern Africa/Africa","international","specialist/professional community irrespective of country","don't know"],
 authority:["formal qualifications","professional experience","many years in field","original research","lived/personal experience","unusual access","previous books","articles/papers/published writing","teaching/training/public speaking","recognised reputation","existing audience/community","strong storytelling ability","no formal authority, but worthwhile story/idea","other"],
 established:["interested outsider","interested and learning","some relevant experience","well-established in a field or community","recognised specialist or practitioner","significant public/professional reputation"],
 platform:["newsletter","social following","professional network","academic network","clients/customers","students","speaking engagements","media exposure","religious/community organisation","existing readers","none yet"],
 material:["idea only","notes/fragments","<10k words","10k–30k","30k–60k",">60k","complete manuscript","substantial non-text material such as audio/video/research"],
 needs:["defining the book","structure","more writing","research","developmental editing","cutting/tightening","making specialist material accessible","improving prose","fact/evidence checking","audience identification","commercial positioning","publishing/distribution","unsure"],
 openness:["strongly open","open within reason","prefer light changes","essentially final"],
 market:["yes and know differentiation","yes but differentiation still developing","probably but not researched","don't know any","believe nothing quite like it exists"],
 success:["commercial sales","small but important audience","international readership","professional reputation","influence debate/public understanding","support existing profession/business","preserve legacy/story","establish author identity","create series/body of work","simply reach readers","unsure"],
 barriers:["didn't know where to start","difficulty turning knowledge/material into a book","lack of time","started/stopped repeatedly","structure/writing problems","publisher/agent rejection","little/no response from publishers","assumed publishers would not be interested","cost concerns","don't understand publishing process","nothing; only starting now","other"]
};
function esc(value){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function choices(key, items, multi=false, limit=0){const selected=model[key]|| (multi?[]:"");return `<div class="option-grid">${items.map((v,i)=>`<label class="option"><input type="${multi?"checkbox":"radio"}" name="${key}" value="${esc(v)}" ${multi?selected.includes(v)?"checked":"":selected===v?"checked":""} ${limit?`data-limit="${limit}"`:""}><span>${esc(v)}</span></label>`).join("")}</div>`;}
function q(title,help,body){return `<h2 class="question-title">${title}</h2><p class="question-help">${help||""}</p>${body}`;}
function textarea(key,label,help){return `<div class="field"><label for="${key}">${label}</label><textarea id="${key}" data-text="${key}" maxlength="1000" placeholder="Write plainly; a rough description is fine.">${esc(model[key]||"")}</textarea><small>${help||""}</small></div>`;}
function isFiction(){return fiction.includes(model.publication_type);}
function fields(){switch(step){
case 0:return q("Where is the project now?","Choose the closest description.",choices("project_stage",options.stage));
case 1:return q("What kind of book is it?","If it crosses categories, choose the closest starting point.",choices("publication_type",options.type));
case 2:return q("Language and the central idea","Tell us the intended publication language, then describe what a reader would get from this book.",choices("publication_language",options.language)+textarea("concept_summary","In one or two sentences, what is the book?","A simple description is enough."));
case 3:return q("Why this book, and for whom?","Choose as many as are useful.",`<h3>Why should this book exist?</h3>${choices("why_exists",options.why,true)}<h3 style="margin-top:24px">Intended readers</h3>${choices("audience_types",options.readers,true)}`);
case 4:return q("Audience and reach","Neither a specialist audience nor a broad audience is automatically better.",`<div class="field"><label for="niche">How specialised is the likely readership?</label><div class="range-row"><span>1 · very specialised</span><span>5 · very broad</span></div><input class="range" id="niche" type="range" min="1" max="5" value="${model.niche_level}" data-range="niche_level"></div><h3>Geographic/market reach</h3>${choices("geographic_market",options.reach)}`);
case 5:return q("Your fit for this project","Formal credentials are not the only kind of authority. Lived experience, storytelling and access can matter too.",`<h3>Author fit / authority</h3>${choices("author_authority",options.authority,true)}<h3 style="margin-top:24px">How established are you in this area?</h3>${choices("author_establishment",options.established)}`);
case 6:return q("Reach and current material","An existing platform can help, but having none yet does not rule a project out.",`<h3>Existing reach / platform</h3>${choices("author_platform",options.platform,true)}<h3 style="margin-top:24px">Current material</h3>${choices("material_volume",options.material)}`);
case 7:return q("What would help the project move forward?","Choose every development need that feels relevant.",`${choices("development_needs",options.needs,true)}<h3 style="margin-top:24px">Openness to substantial editorial change</h3>${choices("development_openness",options.openness)}`);
case 8:return q("Market awareness and your own definition of success","Knowing comparable books is useful; a project being unusual is not, by itself, a strength or a weakness.",`<h3>Awareness of comparable / competing books</h3>${choices("market_awareness",options.market)}<h3 style="margin-top:24px">Desired definition of success <small>(choose up to three)</small></h3>${choices("success_goal",options.success,true,3)}`);
case 9:return q("What has held it back?","This helps us understand the practical challenge, not judge the project.",choices("previous_barriers",options.barriers,true));
case 10:return branch(); default:return "";}}
function branch(){if(isFiction())return q("A little more about the fiction","These answers help us understand reader expectations.",`<h3>Strongest reader appeal</h3>${choices("fiction_appeal",["plot/suspense","romance","characters","humour","setting/world","emotional experience","genre satisfaction","unusual/original element","unsure"])}<h3 style="margin-top:24px">Clarity about genre / shelf</h3>${choices("genre_clarity",["very clear","roughly clear","not yet clear"])}`);if(model.publication_type==="Children's book")return q("A little more about the children's book","We are not trying to apply detailed children's-market scoring at this stage.",`<div class="field"><label for="age_range">Intended age range</label><input id="age_range" data-text="age_range" value="${esc(model.age_range||"")}" placeholder="For example: 5–7, middle grade, or young readers"></div><h3>Is illustration central to the book?</h3>${choices("illustration_central",["yes","no","not sure yet"])}`);return q("Ready for an initial view","Review your answers, then see a development-friendly initial assessment. A closer judgement would always require looking at the project or material itself.",`<div class="notice">Your answers remain in this browser for this assessment. They are not sent anywhere at this stage.</div>`);}
function persist(){app.querySelectorAll("input[type=radio]:checked").forEach(el=>model[el.name]=el.value);app.querySelectorAll(".option-grid").forEach(box=>{const c=box.querySelector("input[type=checkbox]");if(c)model[c.name]=[...box.querySelectorAll("input:checked")].map(el=>el.value)});app.querySelectorAll("[data-text]").forEach(el=>model[el.dataset.text]=el.value.trim());app.querySelectorAll("[data-range]").forEach(el=>model[el.dataset.range]=Number(el.value));}
function valid(){let required=[];switch(step){case 0:required=["project_stage"];break;case 1:required=["publication_type"];break;case 2:required=["publication_language","concept_summary"];break;case 3:required=["why_exists","audience_types"];break;case 4:required=["geographic_market"];break;case 5:required=["author_authority","author_establishment"];break;case 6:required=["author_platform","material_volume"];break;case 7:required=["development_needs","development_openness"];break;case 8:required=["market_awareness","success_goal"];break;case 9:required=["previous_barriers"];break;case 10:if(isFiction())required=["fiction_appeal","genre_clarity"];if(model.publication_type==="Children's book")required=["age_range","illustration_central"];break;}return required.every(key=>Array.isArray(model[key])?model[key].length:Boolean(model[key]));}
function render(){const total=11;app.innerHTML=`<div class="progress-top"><span>Step ${Math.min(step+1,total)} of ${total}</span><span>${Math.round((step+1)/total*100)}%</span></div><div class="progress"><span style="width:${(step+1)/total*100}%"></span></div><div id="question">${fields()}</div><p class="error" id="error" hidden>Please answer this question before continuing.</p><div class="actions"><button class="button secondary" id="back" ${step===0?"disabled":""}>Back</button><button class="button" id="next">${step===10?"See my initial view":"Continue"}</button></div>`;$("#back").onclick=()=>{persist();step--;render()};$("#next").onclick=()=>{persist();if(!valid()){$("#error").hidden=false;return}if(step===10){results();return}step++;render()};app.querySelectorAll("input[data-limit]").forEach(el=>el.addEventListener("change",()=>{const checked=app.querySelectorAll(`input[name="${el.name}"]:checked`);if(checked.length>Number(el.dataset.limit)){el.checked=false;$("#error").textContent=`Please choose up to ${el.dataset.limit}.`;$("#error").hidden=false}}));}
function score(){const s={"Concept Potential":10,"Audience Potential":8,"Author Fit":8,"Publication Fit":8,"Project Readiness":7};if(model.concept_summary.length>35)s["Concept Potential"]+=4;if(model.why_exists.length>=2)s["Concept Potential"]+=3;if(isFiction()&&model.fiction_appeal!=="unsure")s["Concept Potential"]+=2;if(model.audience_types.length>=1)s["Audience Potential"]+=4;if(model.geographic_market!=="don't know")s["Audience Potential"]+=2;if(model.author_authority.length>=2)s["Author Fit"]+=5;if(isFiction()||["Memoir/autobiography/biography","Family history/genealogy"].includes(model.publication_type)||model.author_authority.some(x=>["lived/personal experience","strong storytelling ability"].includes(x)))s["Author Fit"]+=3;if(model.market_awareness.startsWith("yes"))s["Publication Fit"]+=4;if(["Technical/professional work or manual","Academic/specialist knowledge for a broader audience"].includes(model.publication_type)&&model.author_authority.length)s["Publication Fit"]+=3;if(model.development_openness==="strongly open")s["Project Readiness"]+=5;else if(model.development_openness==="open within reason")s["Project Readiness"]+=3;if(!["idea only","notes/fragments"].includes(model.material_volume))s["Project Readiness"]+=4;Object.keys(s).forEach(k=>s[k]=Math.min(20,s[k]));return s;}
function observations(scores){const notes=[];if(model.publication_type==="Family history/genealogy")notes.push("Family value, preservation and legacy can be meaningful aims even where the likely readership is small.");if(["Technical/professional work or manual","Academic/specialist knowledge for a broader audience"].includes(model.publication_type))notes.push("For this kind of project, expertise, accuracy and usefulness to a defined specialist audience matter more than mass-market scale.");if(isFiction())notes.push(model.genre_clarity==="not yet clear"?"Clarifying the likely genre and the reader experience it promises would be a useful next step.":"You have begun to identify the reader appeal and genre expectations that will help shape the book.");if(model.material_volume==="idea only"||model.project_stage==="idea only")notes.push("Being early is not a negative: the immediate work is to define a strong book-shaped proposition and structure.");if(model.author_platform.includes("none yet"))notes.push("No existing platform does not disqualify the project; we would consider practical ways to identify and reach its readers.");if(notes.length<2)notes.push("Your answers suggest there is enough here to investigate the audience, positioning and development path more closely.");return notes.slice(0,3);}
function results(){const scores=score(), total=Object.values(scores).reduce((a,b)=>a+b,0);model.potential_scores={...scores,total};const band=total>=80?"Strong potential for closer assessment":total>=65?"Promising project":total>=50?"Worth exploring":total>=35?"Early stage, but potentially developable":"We need to understand the idea better";app.innerHTML=`<section class="result-head"><p class="eyebrow">Initial view</p><div class="score">${total}<small style="font-size:.7rem">/ 100</small></div><h2>${band}</h2><p class="band">${total>=50?"We think this project is worth a closer look.":"There may be something worth developing here; a closer conversation would help us understand it."}</p></section><div class="score-grid">${Object.entries(scores).map(([name,value])=>`<div class="score-item"><b>${value}/20</b><span>${name}</span></div>`).join("")}</div><h2>Our initial view</h2><p>This is a development-friendly first indication, not a publishing offer or a prediction of commercial success. A proper judgement requires closer examination of the project and, where available, the material.</p>${observations(scores).map(note=>`<p class="observation">${esc(note)}</p>`).join("")}<section class="contact"><h2>Would you like us to have a look?</h2><p>There is no charge for this initial contact or for us to decide whether we would like to see more. You are not committing to any paid service.</p><form id="contact-form" novalidate><div class="field"><label for="name">Name</label><input id="name" required></div><div class="field"><label for="email">Email</label><input id="email" type="email" required></div><div class="field"><label for="country">Country</label><input id="country" required></div><div class="field"><label for="preferred-language">Preferred language</label><input id="preferred-language" required></div><div class="field"><label for="phone">Optional phone / WhatsApp</label><input id="phone"></div><div class="field"><label for="note">Brief note</label><textarea id="note"></textarea></div><label class="checkbox"><input id="consent" type="checkbox" required><span>I consent to Clear Copy Clinic contacting me about this project.</span></label><p class="error" id="contact-error" hidden>Please complete the required fields and consent to being contacted.</p><button class="button" style="margin-top:22px" type="submit">Send initial enquiry</button></form><p class="notice" style="margin-top:22px">For this MVP, the assessment is not stored or sent automatically. Contact details are prepared only when you choose to send this enquiry.</p></section>`;$("#contact-form").addEventListener("submit",contact);window.scrollTo({top:0,behavior:"smooth"});}
function contact(event){event.preventDefault();const f=event.currentTarget;if(!f.checkValidity()){$("#contact-error").hidden=false;return}const body=`Book project enquiry\n\nName: ${$("#name").value}\nEmail: ${$("#email").value}\nCountry: ${$("#country").value}\nPreferred language: ${$("#preferred-language").value}\nPhone/WhatsApp: ${$("#phone").value}\n\nBook: ${model.concept_summary}\n\nNote: ${$("#note").value}`;window.location.href=`mailto:hello@clearcopy.clinic?subject=${encodeURIComponent("Book project initial enquiry")}&body=${encodeURIComponent(body)}`;}
render();
